import { useState } from "react";
import { api } from "../../lib/api-client";

export function DeliveryPage() {
  const [cards, setCards] = useState(""); const [batchId, setBatchId] = useState(""); const [status, setStatus] = useState<Record<string, unknown> | null>(null); const [message, setMessage] = useState("");
  async function prepare() { try { const result = await api.deliveries.create({ card_ids: cards.split(",").map((value) => value.trim()).filter(Boolean), language: "zh", attachment_mode: "png" }, crypto.randomUUID()); const data = result.data as { id: string }; setBatchId(data.id); setMessage("QRZ 收件人准备中，请稍后刷新状态。"); } catch (error) { setMessage(error instanceof Error ? error.message : "创建发卡预览失败"); } }
  async function refresh() { if (!batchId) return; try { const result = await api.deliveries.get(batchId); setStatus(result.data); } catch (error) { setMessage(error instanceof Error ? error.message : "读取状态失败"); } }
  async function send() { if (!status || !batchId) return; const items = (status.items as Array<{ delivery_id?: string; preparation_status?: string }> | undefined) ?? []; const ids = items.filter((item) => item.preparation_status === "ready" && item.delivery_id).map((item) => item.delivery_id!); try { await api.deliveries.send(batchId, { delivery_ids: ids, preview_version: Number(status.version) }); setMessage(`已提交 ${ids.length} 张，外部邮件仍以服务端回执为准。`); } catch (error) { setMessage(error instanceof Error ? error.message : "提交发卡失败"); } }
  return <section className="page-section"><header className="page-header"><div><p className="eyebrow">DELIVERY</p><h1>QRZ 电子发卡</h1><p className="muted">预览阶段只查询目录，不会自动发送；确认后才进入发送队列。</p></div></header><div className="form-card"><label>已发布卡片 ID（逗号分隔）<input value={cards} onChange={(event) => setCards(event.target.value)} placeholder="card_a,card_b" /></label><div className="button-row"><button type="button" className="primary-button" disabled={!cards} onClick={() => void prepare()}>创建预览</button><button type="button" onClick={() => void refresh()} disabled={!batchId}>刷新</button><button type="button" onClick={() => void send()} disabled={!status}>确认发送</button></div>{batchId && <p className="muted">批次：{batchId}</p>}{status && <pre className="code-block">{JSON.stringify(status, null, 2)}</pre>}{message && <p role="status" className="muted">{message}</p>}</div></section>;
}
