import { useEffect, useState } from "react";
import { api } from "../../lib/api-client";

export function AgentSettingsPage() {
  const [agents, setAgents] = useState<Array<Record<string, unknown>>>([]); const [name, setName] = useState(""); const [stationId, setStationId] = useState(""); const [stationCallsign, setStationCallsign] = useState(""); const [sourceInstance, setSourceInstance] = useState<string>(crypto.randomUUID()); const [token, setToken] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { setAgents((await api.integrations.listAgents()).data); } catch (error) { setMessage(error instanceof Error ? error.message : "读取设备失败"); } }
  useEffect(() => { void load(); }, []);
  async function create() { try { const result = await api.integrations.createAgent({ name, profiles: [{ station_id: Number(stationId), source_kind: "wsjtx", source_instance: sourceInstance, expected_station_callsign: stationCallsign }] }); setToken(String((result.data as { token?: string }).token ?? "")); setName(""); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "设备创建失败：请确认台站 ID 与呼号配置"); } }
  return <section className="page-section"><header className="page-header"><div><p className="eyebrow">INTEGRATIONS</p><h1>无线电代理设备</h1><p className="muted">设备令牌只显示一次；代理权限与 Owner 登录完全隔离。</p></div></header><div className="form-card"><label>设备名称<input value={name} onChange={(event) => setName(event.target.value)} placeholder="FT8 主机" /></label><label>台站 ID<input value={stationId} onChange={(event) => setStationId(event.target.value)} inputMode="numeric" placeholder="1" /></label><label>台站呼号<input value={stationCallsign} onChange={(event) => setStationCallsign(event.target.value)} placeholder="BA4RC" /></label><label>来源实例 UUID<input value={sourceInstance} onChange={(event) => setSourceInstance(event.target.value)} /></label><p className="muted">服务端会用所选台站呼号校验 profile；高级 N1MM 配置请通过 API 设置。</p><div className="button-row"><button type="button" className="primary-button" disabled={!name || !stationId || !stationCallsign} onClick={() => void create()}>创建设备</button><a className="button" href="/admin/settings/integrations/review">打开异常收件箱</a></div>{token && <p role="status" className="code-block">请立即保存一次性令牌：{token}</p>}{message && <p className="muted">{message}</p>}</div><div className="table-card"><h2>已登记设备</h2>{agents.map((agent) => <div className="list-row" key={String(agent.id)}><span>{String(agent.name)} · {String(agent.id)}</span><span className="muted">{agent.revoked_at ? "已吊销" : "有效"}</span></div>)}</div></section>;
}
