import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

interface ParsedProp {
  name: string;
  type: string;
  nullable: boolean;
  isRequired: boolean;
  enumValues?: string[];
  rawType?: string;
}

interface ParsedSchema {
  name: string;
  properties: ParsedProp[];
}

export function parseSchemasFromYaml(yamlText: string): Record<string, ParsedSchema> {
  const lines = yamlText.split("\n");
  const schemas: Record<string, ParsedSchema> = {};
  let currentSchema: ParsedSchema | null = null;
  let inComponentsSchemas = false;
  let inProperties = false;
  let inRequired = false;
  let currentProp: Partial<ParsedProp> | null = null;
  let inEnum = false;
  const requiredSet = new Set<string>();

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === "components:") {
      continue;
    }
    if (line.startsWith("  schemas:")) {
      inComponentsSchemas = true;
      continue;
    }
    if (!inComponentsSchemas) continue;

    if (line.match(/^ {2}[a-zA-Z0-9_-]+:/) && !line.startsWith("  schemas:")) {
      if (currentSchema) {
        for (const p of currentSchema.properties) {
          p.isRequired = requiredSet.has(p.name);
        }
        schemas[currentSchema.name] = currentSchema;
      }
      break;
    }

    const schemaMatch = line.match(/^ {4}([A-Za-z0-9_]+):$/);
    if (schemaMatch) {
      if (currentSchema) {
        for (const p of currentSchema.properties) {
          p.isRequired = requiredSet.has(p.name);
        }
        schemas[currentSchema.name] = currentSchema;
      }
      requiredSet.clear();
      currentSchema = { name: schemaMatch[1], properties: [] };
      inProperties = false;
      inRequired = false;
      currentProp = null;
      inEnum = false;
      continue;
    }

    if (!currentSchema) continue;

    if (line.startsWith("      properties:")) {
      inProperties = true;
      inRequired = false;
      continue;
    }
    if (line.startsWith("      required:")) {
      inProperties = false;
      inRequired = true;
      continue;
    }

    if (inRequired) {
      const reqMatch = line.match(/^ {8}- (.+)$/);
      if (reqMatch) {
        requiredSet.add(reqMatch[1].trim());
      }
      continue;
    }

    if (inProperties) {
      const propMatch = line.match(/^ {8}([A-Za-z0-9_]+):$/);
      if (propMatch) {
        currentProp = { name: propMatch[1], nullable: false, isRequired: false };
        currentSchema.properties.push(currentProp as ParsedProp);
        inEnum = false;
        continue;
      }

      if (currentProp) {
        const typeMatch = line.match(/^ {10}type:\s*(.+)$/);
        if (typeMatch) {
          currentProp.rawType = typeMatch[1].trim();
        }
        if (line.match(/^ {10}nullable:\s*true$/)) {
          currentProp.nullable = true;
        }
        if (line.match(/^ {10}enum:$/)) {
          inEnum = true;
          currentProp.enumValues = [];
          continue;
        }
        if (inEnum) {
          const enumMatch = line.match(/^ {12}- (.+)$/);
          if (enumMatch) {
            currentProp.enumValues?.push(enumMatch[1].trim());
            continue;
          } else {
            inEnum = false;
          }
        }
      }
    }
  }

  if (currentSchema) {
    for (const p of currentSchema.properties) {
      p.isRequired = requiredSet.has(p.name);
    }
    schemas[currentSchema.name] = currentSchema;
  }

  return schemas;
}

function renderProperty(schema: string, prop: ParsedProp): string {
  let tsType = "string";
  if (prop.enumValues && prop.enumValues.length > 0) {
    tsType = prop.enumValues.map((v) => JSON.stringify(v)).join(" | ");
  } else if (prop.rawType === "integer") {
    tsType = "number";
  } else if (prop.rawType === "boolean") {
    tsType = (schema === "StationRecord" && prop.name === "is_default") ? "boolean | number" : "boolean";
  } else if (prop.rawType === "string") {
    tsType = "string";
  } else if (prop.rawType === "array") {
    tsType = "unknown[]";
  }

  if (prop.nullable) {
    tsType += " | null";
  }

  const optional = prop.isRequired ? "" : "?";
  return `  ${prop.name}${optional}: ${tsType};`;
}

export function generateApiTypes(schemas: Record<string, ParsedSchema>): string {
  const parts: string[] = [
    "// This file is auto-generated by scripts/generate-api-client.mts. DO NOT EDIT.",
    'export type { CardTemplate, QsoInput, StationInput } from "@myqsl/domain";\n'
  ];

  const TARGET_SCHEMAS = ["QsoRecord", "StationRecord", "CardTemplateRow", "CardRow", "PublicCardSummary"];

  for (const name of TARGET_SCHEMAS) {
    const s = schemas[name];
    if (!s) continue;
    parts.push(`export interface ${name} {`);
    for (const prop of s.properties) {
      parts.push(renderProperty(name, prop));
      if (name === "QsoRecord" && prop.name === "adif_extra_json") {
        parts.push("  adif_extra?: Record<string, string>;");
      }
    }
    parts.push("}\n");
  }

  return parts.join("\n");
}

async function main() {
  const openapiPath = resolve(process.cwd(), "openapi/myQSL-v1.yaml");
  const yamlText = await readFile(openapiPath, "utf-8");
  const schemas = parseSchemasFromYaml(yamlText);
  const code = generateApiTypes(schemas);

  const outPath = resolve(process.cwd(), "apps/web/src/lib/api-types.ts");
  await writeFile(outPath, code, "utf-8");
  console.log("Generated typed API definitions from OpenAPI at: " + outPath);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
