import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { eqsrOpenApiSpec } from "../packages/domain/src/index.ts";

function toYaml(obj: unknown, indent = 0): string {
  const spaces = " ".repeat(indent);
  if (obj === null || obj === undefined) return "null\n";
  if (typeof obj === "boolean" || typeof obj === "number") return `${obj}\n`;
  if (typeof obj === "string") {
    if (obj.includes("\n") || obj.includes(":") || obj.includes("#") || obj.includes("{") || obj.includes("}") || obj.includes("[") || obj.includes("]") || obj.includes(",") || obj.includes("&") || obj.includes("*") || obj.includes("?") || obj.includes("|") || obj.includes("-") || obj.includes("<") || obj.includes(">") || obj.includes("=") || obj.includes("!") || obj.includes("%") || obj.includes("@") || obj.includes("`") || obj === "" || !isNaN(Number(obj))) {
      return JSON.stringify(obj) + "\n";
    }
    return `${obj}\n`;
  }
  if (Array.isArray(obj)) {
    if (obj.length === 0) return "[]\n";
    let res = "\n";
    for (const item of obj) {
      if (typeof item === "object" && item !== null && !Array.isArray(item)) {
        const itemYaml = toYaml(item, indent + 2).trimStart();
        res += `${spaces}- ${itemYaml}`;
      } else {
        res += `${spaces}- ${toYaml(item, indent + 2).trimStart()}`;
      }
    }
    return res;
  }
  if (typeof obj === "object") {
    const keys = Object.keys(obj as Record<string, unknown>);
    if (keys.length === 0) return "{}\n";
    let res = "\n";
    for (const key of keys) {
      const val = (obj as Record<string, unknown>)[key];
      const formattedKey = /^[a-zA-Z0-9_-]+$/.test(key) ? key : JSON.stringify(key);
      if (typeof val === "object" && val !== null) {
        res += `${spaces}${formattedKey}:${toYaml(val, indent + 2)}`;
      } else {
        res += `${spaces}${formattedKey}: ${toYaml(val, indent + 2).trimStart()}`;
      }
    }
    return res;
  }
  return `${obj}\n`;
}

async function main() {
  const yamlContent = "# This file is auto-generated by scripts/generate-openapi.mts. DO NOT EDIT.\n" + toYaml(eqsrOpenApiSpec).trim() + "\n";
  const outPath = resolve(process.cwd(), "openapi/eQSR-v1.yaml");
  await writeFile(outPath, yamlContent, "utf-8");
  console.log(`Generated OpenAPI 3.1 YAML at: ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
