// This file is auto-generated by scripts/generate-api-client.mts. DO NOT EDIT.
export type { CardTemplate, QsoInput, StationInput } from "@eqsr/domain";

export interface QsoRecord {
  id: number;
  station_id: number | null;
  station_callsign: string;
  call: string;
  qso_date: string;
  time_on: string;
  band: string;
  mode: string;
  submode: string | null;
  freq_mhz: string | null;
  rst_sent: string | null;
  rst_rcvd: string | null;
  gridsquare: string | null;
  name: string | null;
  qth: string | null;
  comment: string | null;
  adif_extra_json?: string;
  adif_extra?: Record<string, string>;
  version: number;
  deleted_at: number | null;
  created_at: number;
  updated_at: number;
}

export interface StationRecord {
  id: number;
  callsign: string;
  station_callsign?: string | null;
  operator_callsign?: string | null;
  grid_square?: string | null;
  qth?: string | null;
  rig?: string | null;
  antenna?: string | null;
  power_w?: number | null;
  is_default: boolean | number;
  version: number;
  created_at?: number;
  updated_at?: number;
}

export interface CardTemplateRow {
  id: number;
  name: string;
  schema_version: number;
  base_width: number;
  base_height: number;
  layout_json: string;
  background_r2_key: string | null;
  background_sha256: string | null;
  version: number;
  created_at?: number;
  updated_at?: number;
}

export interface CardRow {
  id: string;
  public_id: string;
  qso_id: number;
  template_id: number;
  status: "draft" | "ready" | "published" | "void";
  qso_snapshot_json?: string;
  template_snapshot_json?: string;
  image_r2_key?: string | null;
  image_sha256?: string | null;
  lookup_call?: string | null;
  lookup_qso_date?: string | null;
  version?: number;
  created_at: number;
  updated_at: number;
}

export interface PublicCardSummary {
  public_id: string;
  call: string;
  qso_date: string;
  created_at: number;
}
